appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: fW1IfdmmBIBxd5N1wD2e2MeKEQce3H2ccmCp5qcBzZIY0yTPuuIYg7OWHxodKhhv0Bg+EbE2JkxNdMFu+ZYHiRYgu+TLt4UXhuAk9gnG7GisRPH9xWKWCAsd3z014M2S+DG993yBxmiJH1L2Lf1C7Lc1Lk1gavZtn7N72F25pqo3xrYQouChmPCKQyQ6kSQzuBoW4+16WVn8+MJ8uMekeOhPKfcxkCLkYDIB9rSRQ2OHfnkRpHaxg51lUuGHLhYi2KxLRLif0wxkZYGWz2lvhF/pfn3tB0V+1yP6+gAUQ4f7l7Feqv+FKHBxwRJpH5z+eUzT6qn/gL9UhpEPPK66S+tfaRgbpbYmHTHd1w2oe/OvznEm/s3oqkesvllhZD89AO3hHlW3/Epq+MESREKMynwX9wJOz6lJg7+3lmUmvzvznVRQif5Y6rSYHy6ck/juJ+PnbxzT60e6qP7ByV1m4kB6ygdR7/5Thkouzoq3g2ooyCqwzYokPEOj1o8iC1BFODPRQNWAIDe//Z22i5SQVfktgpHWr8le4ZKlhK6cYCg+k6H7TebppOuvnfsXjXoRhfYCbSYahNENLtzhAYtVQCBNJPSWK7fAOGNxvutCXqXvKm4QaRNI2qRlEmvuUpIBcjyyr0nZcAcAtr7idfekpKSlBUUS9NwFPT4+izQSPN4=
conda_forge_output_validation: true
